factories = {
    "StellarTech_Manufacturing": {
        "Name": "StellarTech Manufacturing",
        "Location": "Orbiting Moon Delta",
        "Size": "Large",
        "Type": "Manufacturing",
        "Production Capacity": "High",
        "Input Resources": ["Alloy", "Electronics"],
        "Output Products": ["Spacecraft Components", "Advanced Machinery"],
        "Technology Level": "High",
        "Workforce Size": "Moderate",
        "Automation Level": "High",
        "Energy Source": "Fusion",
        "Environmental Impact": "Low",
        "Security Measures": "High",
        "Economic Status": "Profitable",
        "Ownership": "Corporate",
        "Market Dependence": "High",
        "Expansion Capability": "Moderate",
        "Operational Efficiency": "High",
        "Research and Development Facilities": "Extensive",
        "Affiliations": "Multiple Trade Alliances"
    },
    "AstraChem_Refinery": {
        "Name": "AstraChem Refinery",
        "Location": "Planet Zephyr",
        "Size": "Medium",
        "Type": "Refining",
        "Production Capacity": "Moderate",
        "Input Resources": ["Crude Oil", "Gas"],
        "Output Products": ["Fuel", "Plastics"],
        "Technology Level": "Medium",
        "Workforce Size": "High",
        "Automation Level": "Moderate",
        "Energy Source": "Solar",
        "Environmental Impact": "High",
        "Security Measures": "Moderate",
        "Economic Status": "Stable",
        "Ownership": "Private",
        "Market Dependence": "Moderate",
        "Expansion Capability": "Low",
        "Operational Efficiency": "Moderate",
        "Research and Development Facilities": "Limited",
        "Affiliations": "Local Governments"
    },
        "NovaFood_Processors": {
        "Name": "NovaFood Processors",
        "Location": "Colony Vega",
        "Size": "Small",
        "Type": "Food Processing",
        "Production Capacity": "Low",
        "Input Resources": ["Agricultural Products"],
        "Output Products": ["Packaged Food", "Nutrient Bars"],
        "Technology Level": "Medium",
        "Workforce Size": "Low",
        "Automation Level": "High",
        "Energy Source": "Geothermal",
        "Environmental Impact": "Moderate",
        "Security Measures": "Low",
        "Economic Status": "Growing",
        "Ownership": "Cooperative",
        "Market Dependence": "Low",
        "Expansion Capability": "High",
        "Operational Efficiency": "High",
        "Research and Development Facilities": "Moderate",
        "Affiliations": "Agricultural Guilds"
    },
    "Cybernetics_Lab": {
        "Name": "Cybernetics Lab",
        "Location": "Tech Hub Station",
        "Size": "Medium",
        "Type": "High-Tech Production",
        "Production Capacity": "Moderate",
        "Input Resources": ["Electronic Components", "Rare Metals"],
        "Output Products": ["Cybernetic Implants", "AI Cores"],
        "Technology Level": "Advanced",
        "Workforce Size": "Moderate",
        "Automation Level": "Very High",
        "Energy Source": "Nuclear",
        "Environmental Impact": "Low",
        "Security Measures": "Very High",
        "Economic Status": "Highly Profitable",
        "Ownership": "Corporate",
        "Market Dependence": "Moderate",
        "Expansion Capability": "Moderate",
        "Operational Efficiency": "Very High",
        "Research and Development Facilities": "State-of-the-Art",
        "Affiliations": "Technology Consortiums"
    },
    "Aegis_Armaments": {
        "Name": "Aegis Armaments",
        "Location": "Orbiting Fortress Delta",
        "Size": "Large",
        "Type": "Weapons Manufacturing",
        "Production Capacity": "High",
        "Input Resources": ["Titanium", "Plasma Cores"],
        "Output Products": ["Laser Cannons", "Shield Generators"],
        "Technology Level": "Advanced",
        "Workforce Size": "Automated",
        "Automation Level": "Fully Automated",
        "Energy Source": "Nuclear Fusion",
        "Environmental Impact": "Moderate",
        "Security Measures": "Maximum",
        "Economic Status": "Profitable",
        "Ownership": "Private Military Corporation",
        "Market Dependence": "High (Military Contracts)",
        "Expansion Capability": "Moderate",
        "Operational Efficiency": "Optimized",
        "Research and Development Facilities": "Top-Secret",
        "Affiliations": "Galactic Defense Contractors"
    },
    "Zenon_Biotech": {
        "Name": "Zenon Biotech",
        "Location": "Planet Greenhaven",
        "Size": "Medium",
        "Type": "Biomedical Production",
        "Production Capacity": "Specialized",
        "Input Resources": ["Genetic Material", "Pharmaceutical Compounds"],
        "Output Products": ["Medical Implants", "Bio-Enhancers"],
        "Technology Level": "State-of-the-Art",
        "Workforce Size": "Highly Skilled",
        "Automation Level": "Moderate",
        "Energy Source": "Renewable",
        "Environmental Impact": "Low",
        "Security Measures": "High",
        "Economic Status": "Growing",
        "Ownership": "Healthcare Consortium",
        "Market Dependence": "Stable",
        "Expansion Capability": "High",
        "Operational Efficiency": "High",
        "Research and Development Facilities": "Advanced",
        "Affiliations": "Medical Research Institutions"
    },
        "Quantum_Core_Foundry": {
        "Name": "Quantum Core Foundry",
        "Location": "Asteroid Belt ZK-5",
        "Size": "Small",
        "Type": "High-Tech Manufacturing",
        "Production Capacity": "Low",
        "Input Resources": ["Exotic Minerals", "Quantum Particles"],
        "Output Products": ["Quantum Processors", "Advanced AI Cores"],
        "Technology Level": "Highly Advanced",
        "Workforce Size": "Specialized Engineers",
        "Automation Level": "High",
        "Energy Source": "Solar and Quantum Energy",
        "Environmental Impact": "Minimal",
        "Security Measures": "Extremely High",
        "Economic Status": "Niche Market",
        "Ownership": "Tech Research Conglomerate",
        "Market Dependence": "Critical for High-Tech Sector",
        "Expansion Capability": "Limited",
        "Operational Efficiency": "Highly Efficient",
        "Research and Development Facilities": "Cutting-Edge",
        "Affiliations": "Advanced Technology Institutes"
    },
    "Galactic_Hydroponics": {
        "Name": "Galactic Hydroponics",
        "Location": "Orbiting Colony XG-3",
        "Size": "Large",
        "Type": "Agricultural",
        "Production Capacity": "High",
        "Input Resources": ["Water", "Organic Nutrients"],
        "Output Products": ["Food Crops", "Medicinal Plants"],
        "Technology Level": "Moderate",
        "Workforce Size": "Moderate",
        "Automation Level": "Moderate",
        "Energy Source": "Hydro and Solar Power",
        "Environmental Impact": "Eco-Friendly",
        "Security Measures": "Moderate",
        "Economic Status": "Essential",
        "Ownership": "Agricultural Cooperative",
        "Market Dependence": "High (Food Supply)",
        "Expansion Capability": "High",
        "Operational Efficiency": "Optimized",
        "Research and Development Facilities": "Focused on Agricultural Innovations",
        "Affiliations": "Food Distribution Networks"
    }
}



