factories = {
    "StellarTech_Manufacturing": {
        "Name": "StellarTech Manufacturing",
        "Location": "Orbiting Moon Delta",
        "Size": "Large",
        "Type": "Manufacturing",
        "Production Capacity": "High",
        "Input Resources": ["Alloy", "Electronics"],
        "Output Products": ["Spacecraft Components", "Advanced Machinery"],
        "Technology Level": "High",
        "Workforce Size": "Moderate",
        "Automation Level": "High",
        "Energy Source": "Fusion",
        "Environmental Impact": "Low",
        "Security Measures": "High",
        "Economic Status": "Profitable",
        "Ownership": "Corporate",
        "Market Dependence": "High",
        "Expansion Capability": "Moderate",
        "Operational Efficiency": "High",
        "Research and Development Facilities": "Extensive",
        "Affiliations": "Multiple Trade Alliances"
    },
    "AstraChem_Refinery": {
        "Name": "AstraChem Refinery",
        "Location": "Planet Zephyr",
        "Size": "Medium",
        "Type": "Refining",
        "Production Capacity": "Moderate",
        "Input Resources": ["Crude Oil", "Gas"],
        "Output Products": ["Fuel", "Plastics"],
        "Technology Level": "Medium",
        "Workforce Size": "High",
        "Automation Level": "Moderate",
        "Energy Source": "Solar",
        "Environmental Impact": "High",
        "Security Measures": "Moderate",
        "Economic Status": "Stable",
        "Ownership": "Private",
        "Market Dependence": "Moderate",
        "Expansion Capability": "Low",
        "Operational Efficiency": "Moderate",
        "Research and Development Facilities": "Limited",
        "Affiliations": "Local Governments"
    },
        "NovaFood_Processors": {
        "Name": "NovaFood Processors",
        "Location": "Colony Vega",
        "Size": "Small",
        "Type": "Food Processing",
        "Production Capacity": "Low",
        "Input Resources": ["Agricultural Products"],
        "Output Products": ["Packaged Food", "Nutrient Bars"],
        "Technology Level": "Medium",
        "Workforce Size": "Low",
        "Automation Level": "High",
        "Energy Source": "Geothermal",
        "Environmental Impact": "Moderate",
        "Security Measures": "Low",
        "Economic Status": "Growing",
        "Ownership": "Cooperative",
        "Market Dependence": "Low",
        "Expansion Capability": "High",
        "Operational Efficiency": "High",
        "Research and Development Facilities": "Moderate",
        "Affiliations": "Agricultural Guilds"
    },
    "Cybernetics_Lab": {
        "Name": "Cybernetics Lab",
        "Location": "Tech Hub Station",
        "Size": "Medium",
        "Type": "High-Tech Production",
        "Production Capacity": "Moderate",
        "Input Resources": ["Electronic Components", "Rare Metals"],
        "Output Products": ["Cybernetic Implants", "AI Cores"],
        "Technology Level": "Advanced",
        "Workforce Size": "Moderate",
        "Automation Level": "Very High",
        "Energy Source": "Nuclear",
        "Environmental Impact": "Low",
        "Security Measures": "Very High",
        "Economic Status": "Highly Profitable",
        "Ownership": "Corporate",
        "Market Dependence": "Moderate",
        "Expansion Capability": "Moderate",
        "Operational Efficiency": "Very High",
        "Research and Development Facilities": "State-of-the-Art",
        "Affiliations": "Technology Consortiums"
    }
}