# this file should contain a list of goods, their base price, and a description
# the goods should be science fiction goods
goods = {
    "HydrogenFuel": {"Type": "Raw Material", "Value": 10, "Weight": 1, "Quality": "Standard", "Durability": "Stable", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Simple", "Technological Level": "Low", "Cultural Value": "Low", "Expiration": "None"},
    "QuantumChips": {"Type": "Technology", "Value": 500, "Weight": 0.5, "Quality": "High", "Durability": "Fragile", "Rarity": "Rare", "Legal Status": "Restricted", "Production Requirements": "Complex", "Technological Level": "High", "Cultural Value": "Low", "Expiration": "None"},
    "LuxuryFoods": {"Type": "Foodstuffs", "Value": 100, "Weight": 2, "Quality": "Luxury", "Durability": "Perishable", "Rarity": "Uncommon", "Legal Status": "Legal", "Production Requirements": "Moderate", "Technological Level": "Medium", "Cultural Value": "High", "Expiration": "Short"},
    "AlienArtifacts": {"Type": "Cultural", "Value": 1000, "Weight": 3, "Quality": "Varied", "Durability": "Durable", "Rarity": "Rare", "Legal Status": "Illegal", "Production Requirements": "N/A", "Technological Level": "Unknown", "Cultural Value": "Very High", "Expiration": "None"},
    "MedicalSupplies": {"Type": "Medicinal", "Value": 200, "Weight": 1.5, "Quality": "High", "Durability": "Stable", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Complex", "Technological Level": "High", "Cultural Value": "Medium", "Expiration": "Moderate"},
    "MilitaryHardware": {"Type": "Technology", "Value": 1000, "Weight": 5, "Quality": "High", "Durability": "Stable", "Rarity": "Rare", "Legal Status": "Restricted", "Production Requirements": "Complex", "Technological Level": "High", "Cultural Value": "Low", "Expiration": "None"},
    "StellarMaps": {"Type": "Information", "Value": 300, "Weight": 0, "Quality": "High", "Durability": "N/A", "Rarity": "Uncommon", "Legal Status": "Legal", "Production Requirements": "Specialized", "Technological Level": "Medium", "Cultural Value": "Medium", "Expiration": "None"},
    "RobotParts": {"Type": "Manufactured Goods", "Value": 150, "Weight": 5, "Quality": "Standard", "Durability": "Durable", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Moderate", "Technological Level": "High", "Cultural Value": "Low", "Expiration": "None"},
    "BioGel": {"Type": "Medicinal", "Value": 250, "Weight": 2, "Quality": "High", "Durability": "Stable", "Rarity": "Uncommon", "Legal Status": "Restricted", "Production Requirements": "Complex", "Technological Level": "Advanced", "Cultural Value": "Low", "Expiration": "Long"},
    "ExoticSpices": {"Type": "Luxury Items", "Value": 400, "Weight": 1, "Quality": "Luxury", "Durability": "Perishable", "Rarity": "Rare", "Legal Status": "Legal", "Production Requirements": "Simple", "Technological Level": "Low", "Cultural Value": "High", "Expiration": "Moderate"},
    "NanoFibers": {"Type": "Technology", "Value": 600, "Weight": 0.2, "Quality": "High", "Durability": "Fragile", "Rarity": "Rare", "Legal Status": "Legal", "Production Requirements": "High-tech", "Technological Level": "Advanced", "Cultural Value": "Low", "Expiration": "None"},
    "AncientManuscripts": {"Type": "Cultural", "Value": 800, "Weight": 3, "Quality": "Varied", "Durability": "Fragile", "Rarity": "Very Rare", "Legal Status": "Legal", "Production Requirements": "N/A", "Technological Level": "N/A", "Cultural Value": "Very High", "Expiration": "None"},
    "RareMetals": {"Type": "Raw Material", "Value": 200, "Weight": 5, "Quality": "Standard", "Durability": "Stable", "Rarity": "Uncommon", "Legal Status": "Legal", "Production Requirements": "Simple", "Technological Level": "Low", "Cultural Value": "Low", "Expiration": "None"},
    "PreciousMetals": {"Type": "Raw Material", "Value": 300, "Weight": 5, "Quality": "Standard", "Durability": "Stable", "Rarity": "Rare", "Legal Status": "Legal", "Production Requirements": "Simple", "Technological Level": "Low", "Cultural Value": "Low", "Expiration": "None"},
    "DarkMatterSamples": {"Type": "Research Material", "Value": 1000, "Weight": 0.1, "Quality": "High", "Durability": "Stable", "Rarity": "Extremely Rare", "Legal Status": "Restricted", "Production Requirements": "Advanced", "Technological Level": "Very High", "Cultural Value": "Low", "Expiration": "None"},
    "CyberneticImplants": {"Type": "Technology", "Value": 450, "Weight": 2, "Quality": "High", "Durability": "Durable", "Rarity": "Uncommon", "Legal Status": "Restricted", "Production Requirements": "Complex", "Technological Level": "High", "Cultural Value": "Medium", "Expiration": "None"},
    "PlasmaCoils": {"Type": "Technology", "Value": 350, "Weight": 4, "Quality": "Standard", "Durability": "Durable", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Moderate", "Technological Level": "Medium", "Cultural Value": "Low", "Expiration": "None"},
    "CryogenicContainers": {"Type": "Manufactured Goods", "Value": 200, "Weight": 6, "Quality": "Standard", "Durability": "Durable", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Simple", "Technological Level": "Medium", "Cultural Value": "Low", "Expiration": "None"},
    "StarSteel": {"Type": "Manufactured Goods", "Value": 150, "Weight": 5, "Quality": "High", "Durability": "Durable", "Rarity": "Uncommon", "Legal Status": "Legal", "Production Requirements": "Advanced", "Technological Level": "Medium", "Cultural Value": "Low", "Expiration": "None"},
    "CryoHerbs": {"Type": "Medicinal", "Value": 300, "Weight": 0.2, "Quality": "Premium", "Durability": "Perishable", "Rarity": "Rare", "Legal Status": "Legal", "Production Requirements": "Specific", "Technological Level": "High", "Cultural Value": "Medium", "Expiration": "Short"},
    "HoloProjectors": {"Type": "Technology", "Value": 450, "Weight": 1.2, "Quality": "Standard", "Durability": "Moderate", "Rarity": "Common", "Legal Status": "Legal", "Production Requirements": "Moderate", "Technological Level": "High", "Cultural Value": "Medium", "Expiration": "None"},
    "NeutroniumOre": {"Type": "Raw Material", "Value": 800, "Weight": 10, "Quality": "Raw", "Durability": "Stable", "Rarity": "Very Rare", "Legal Status": "Restricted", "Production Requirements": "Extreme", "Technological Level": "Advanced", "Cultural Value": "Low", "Expiration": "None"}
}
