markets_data = {
    "Galactic_Trade_Bazaar": {
        "Name": "Galactic Trade Bazaar",
        "Location": "Space Station Alpha",
        "Size": "Large",
        "Economic Status": "Prosperous",
        "Market Type": "Commodity Exchange",
        "Specialization": "Raw Materials and Technology",
        "Demand Levels": {"Technology": "High", "Luxury Goods": "Moderate", "Raw Materials": "High"},
        "Supply Levels": {"Technology": "Moderate", "Luxury Goods": "Low", "Raw Materials": "High"},
        "Price Fluctuations": "Moderate",
        "Trade Regulations": "Standard",
        "Accessibility": "High",
        "Reputation": "Reliable",
        "Security Level": "High",
        "Trading Volume": "Extensive",
        "Operational Hours": "24/7",
        "Technology Level": "Advanced",
        "Cultural Influences": "Diverse",
        "Unique Features": "Automated Auction Systems",
        "Vendor Diversity": "High",
        "Special Events": "Monthly Tech Expo"
    },
    "Shadow_Market": {
        "Name": "Shadow Market",
        "Location": "Planet Zentar",
        "Size": "Medium",
        "Economic Status": "Variable",
        "Market Type": "Black Market",
        "Specialization": "Illegal Goods and Information",
        "Demand Levels": {"Weapons": "High", "Contraband": "High", "Information": "High"},
        "Supply Levels": {"Weapons": "Moderate", "Contraband": "High", "Information": "Moderate"},
        "Price Fluctuations": "High",
        "Trade Regulations": "None",
        "Accessibility": "Restricted",
        "Reputation": "Risky",
        "Security Level": "Low",
        "Trading Volume": "Moderate",
        "Operational Hours": "Irregular",
        "Technology Level": "Moderate",
        "Cultural Influences": "Underworld",
        "Unique Features": "Anonymous Trading Systems",
        "Vendor Diversity": "Moderate",
        "Special Events": "Secret Auctions"
    },
    "Intergalactic_Trade_Market": {
        "Name": "Intergalactic Trade Market",
        "Location": "Station Alpha Centauri",
        "Size": "Huge",
        "Economic Status": "Booming",
        "Market Type": "Universal Trading",
        "Specialization": "Wide Range of Goods and Services",
        "Demand Levels": {"High-Tech Goods": "High", "Luxury Items": "Moderate", "Raw Materials": "Steady"},
        "Supply Levels": {"Technology": "Abundant", "Rare Resources": "Variable"},
        "Price Fluctuations": "Frequent",
        "Trade Regulations": "Moderate",
        "Accessibility": "Open to All Traders",
        "Reputation": "Busy and Competitive",
        "Security Level": "High",
        "Trading Volume": "Extremely High",
        "Operational Hours": "Always Open",
        "Technology Level": "Advanced",
        "Cultural Influences": "Diverse",
        "Unique Features": "Automated Auctions, Multicultural Environment",
        "Vendor Diversity": "Extensive",
        "Special Events": "Regular Trade Fairs and Expos"
    },
    "Frontier_Exchange": {
        "Name": "Frontier Exchange",
        "Location": "Outpost Gamma-5",
        "Size": "Small",
        "Economic Status": "Emerging",
        "Market Type": "Local Trade",
        "Specialization": "Frontier Supplies and Raw Materials",
        "Demand Levels": {"Survival Gear": "High", "Construction Materials": "High", "Luxury Items": "Low"},
        "Supply Levels": {"Local Resources": "High", "Imported Goods": "Low"},
        "Price Fluctuations": "Stable",
        "Trade Regulations": "Minimal",
        "Accessibility": "Focused on Local Population",
        "Reputation": "Rustic and Reliable",
        "Security Level": "Moderate",
        "Trading Volume": "Moderate",
        "Operational Hours": "Daylight Hours",
        "Technology Level": "Moderate",
        "Cultural Influences": "Frontier Spirit",
        "Unique Features": "Barter System, Community Gatherings",
        "Vendor Diversity": "Local Traders",
        "Special Events": "Seasonal Harvest Markets"
    },
    "Black_Market_Bazaar": {
        "Name": "Black Market Bazaar",
        "Location": "Undisclosed Location in the Asteroid Belt",
        "Size": "Variable",
        "Economic Status": "Underground",
        "Market Type": "Illicit Trading",
        "Specialization": "Contraband, Rare and Illegal Items",
        "Demand Levels": {"Weapons": "High", "Illegal Tech": "High", "Stolen Artifacts": "Moderate"},
        "Supply Levels": {"Contraband": "Variable", "Black Market Tech": "Unpredictable"},
        "Price Fluctuations": "High",
        "Trade Regulations": "None",
        "Accessibility": "Restricted, Invitation Only",
        "Reputation": "Dangerous but Profitable",
        "Security Level": "Low",
        "Trading Volume": "Unknown",
        "Operational Hours": "Irregular",
        "Technology Level": "Varied",
        "Cultural Influences": "Underworld",
        "Unique Features": "Secretive, Anonymous Transactions",
        "Vendor Diversity": "Shadowy Figures",
        "Special Events": "Rare Auctions of Stolen Goods"
    }
}


