markets = {
    "Galactic_Trade_Bazaar": {
        "Name": "Galactic Trade Bazaar",
        "Location": "Space Station Alpha",
        "Size": "Large",
        "Economic Status": "Prosperous",
        "Market Type": "Commodity Exchange",
        "Specialization": "Raw Materials and Technology",
        "Demand Levels": {"Technology": "High", "Luxury Goods": "Moderate", "Raw Materials": "High"},
        "Supply Levels": {"Technology": "Moderate", "Luxury Goods": "Low", "Raw Materials": "High"},
        "Price Fluctuations": "Moderate",
        "Trade Regulations": "Standard",
        "Accessibility": "High",
        "Reputation": "Reliable",
        "Security Level": "High",
        "Trading Volume": "Extensive",
        "Operational Hours": "24/7",
        "Technology Level": "Advanced",
        "Cultural Influences": "Diverse",
        "Unique Features": "Automated Auction Systems",
        "Vendor Diversity": "High",
        "Special Events": "Monthly Tech Expo"
    },
    "Shadow_Market": {
        "Name": "Shadow Market",
        "Location": "Planet Zentar",
        "Size": "Medium",
        "Economic Status": "Variable",
        "Market Type": "Black Market",
        "Specialization": "Illegal Goods and Information",
        "Demand Levels": {"Weapons": "High", "Contraband": "High", "Information": "High"},
        "Supply Levels": {"Weapons": "Moderate", "Contraband": "High", "Information": "Moderate"},
        "Price Fluctuations": "High",
        "Trade Regulations": "None",
        "Accessibility": "Restricted",
        "Reputation": "Risky",
        "Security Level": "Low",
        "Trading Volume": "Moderate",
        "Operational Hours": "Irregular",
        "Technology Level": "Moderate",
        "Cultural Influences": "Underworld",
        "Unique Features": "Anonymous Trading Systems",
        "Vendor Diversity": "Moderate",
        "Special Events": "Secret Auctions"
    }
}
