missions = {
    "Salvage_Operation": {
        "Mission Name": "Salvage Operation",
        "Description": "Recover valuable cargo from a derelict spacecraft in the asteroid belt.",
        "Objective(s)": ["Navigate to the derelict ship", "Retrieve the cargo", "Return safely"],
        "Mission Type": "Exploration",
        "Difficulty Level": "Medium",
        "Reward": {"Credits": 5000, "Rare Materials": "Quantum Cores"},
        "Time Limit": "3 days",
        "Location": "Asteroid Belt Zeta-3",
        "Client": "Zarco Salvage Company",
        "Required Equipment": ["Salvage Drones", "Cargo Space"],
        "Potential Risks": ["Pirate Attacks", "Asteroid Collisions"],
        "Branching Outcomes": ["Encounter a rival salvager", "Find additional hidden cargo"],
        "Prerequisites": ["Reputation Level 2", "Basic Piloting Skills"],
        "Enemy Types": ["Pirates", "Automated Defense Systems"],
        "Story Tie-ins": "The cargo is rumored to be of alien origin",
        "Unique Features": "Zero-G navigation challenges",
        "Secondary Objectives": ["Map uncharted areas of the asteroid belt"],
        "NPCs Involved": ["Zarco's Agent", "Rival Salvager"],
        "Background Information": "The derelict ship belonged to a notorious smuggler",
        "Success Criteria": "Cargo retrieved and delivered to Zarco's Agent"
    },
    "Diplomatic_Escort": {
        "Mission Name": "Diplomatic Escort",
        "Description": "Provide safe passage for an ambassador to a peace conference on a volatile planet.",
        "Objective(s)": ["Meet the ambassador", "Ensure safe travel", "Thwart any attack attempts"],
        "Mission Type": "Escort",
        "Difficulty Level": "High",
        "Reward": {"Credits": 8000, "Political Favor": "Alliance Pass"},
        "Time Limit": "5 days",
        "Location": "Planet Veridia",
        "Client": "United Planetary Alliance",
        "Required Equipment": ["Combat Ready Ship", "Shield Boosters"],
        "Potential Risks": ["Assassination Attempts", "Space Ambushes"],
        "Branching Outcomes": ["Negotiate with attackers", "Discover a conspiracy"],
        "Prerequisites": ["Reputation Level 3", "Combat Proficiency"],
        "Enemy Types": ["Rebel Fighters", "Mercenaries"],
        "Story Tie-ins": "The peace conference could end a galaxy-wide conflict",
        "Unique Features": "High-stakes diplomatic interactions",
        "Secondary Objectives": ["Gather intelligence on rebel factions"],
        "NPCs Involved": ["Ambassador T'Rel", "Rebel Leader"],
        "Background Information": "Veridia's political situation is delicate and tense",
        "Success Criteria": "Ambassador arrives safely and attends the conference"
    }
}
