organizations = {
    "Galactic_Trading_Corporation": {
        "Name": "Galactic Trading Corporation",
        "Type": "Corporation",
        "Size": "Large",
        "Influence": "High",
        "Reputation": "Respected",
        "Leadership": "CEO Artemis Kline",
        "Economic Power": "Very Strong",
        "Military Strength": "Moderate",
        "Goals/Objectives": "Dominate Galactic Trade Markets",
        "Alliances": ["Various Trade Unions"],
        "Rivalries": ["Competing Corporations", "Pirate Factions"],
        "Operational Area": "Galactic Scale",
        "Membership": "Thousands",
        "Special Capabilities": "Extensive Trade Networks",
        "Legal Status": "Lawful",
        "Ethical Stance": "Profit-driven",
        "Historical Background": "Founded during the early space colonization era",
        "Public Relations": "Strong",
        "Economic Activities": ["Trade", "Resource Extraction"],
        "Cultural Impact": "Significant"
    },
    "United_Planets_Alliance": {
        "Name": "United Planets Alliance",
        "Type": "Government",
        "Size": "Very Large",
        "Influence": "Very High",
        "Reputation": "Stable",
        "Leadership": "Council of Representatives",
        "Economic Power": "Strong",
        "Military Strength": "Very Strong",
        "Goals/Objectives": "Maintain Peace and Order",
        "Alliances": ["Various Planetary Governments"],
        "Rivalries": ["Rebel Groups", "Hostile Governments"],
        "Operational Area": "Multiple Star Systems",
        "Membership": "Billions",
        "Special Capabilities": "Powerful Space Fleet",
        "Legal Status": "Sovereign",
        "Ethical Stance": "Democratic",
        "Historical Background": "Formed after a major galactic conflict",
        "Public Relations": "Focused on Unity",
        "Economic Activities": ["Legislation", "Peacekeeping"],
        "Cultural Impact": "Widespread"
    },
        "Eclipse_Syndicate": {
        "Name": "Eclipse Syndicate",
        "Type": "Syndicate",
        "Size": "Medium",
        "Influence": "Moderate",
        "Reputation": "Notorious",
        "Leadership": "Mysterious Council",
        "Economic Power": "Moderate",
        "Military Strength": "Hidden but Deadly",
        "Goals/Objectives": "Control Underworld Activities",
        "Alliances": ["Smuggler Networks", "Corrupt Officials"],
        "Rivalries": ["Law Enforcement", "Rival Gangs"],
        "Operational Area": "Shadow Regions",
        "Membership": "Hundreds",
        "Special Capabilities": "Espionage and Black Market",
        "Legal Status": "Illegal",
        "Ethical Stance": "Amoral",
        "Historical Background": "Originated from a Fallen Empire",
        "Public Relations": "Non-existent",
        "Economic Activities": ["Smuggling", "Black Market Trading"],
        "Cultural Impact": "Feared and Mythicized"
    },
    "Starwright_Guild": {
        "Name": "Starwright Guild",
        "Type": "Guild",
        "Size": "Small",
        "Influence": "Specialized",
        "Reputation": "Highly Respected",
        "Leadership": "Master Craftsmen",
        "Economic Power": "Focused",
        "Military Strength": "None",
        "Goals/Objectives": "Preserve Crafting Traditions",
        "Alliances": ["Artisans", "Traders"],
        "Rivalries": ["Mass Producers"],
        "Operational Area": "Specific Star Systems",
        "Membership": "Exclusive",
        "Special Capabilities": "Unique Craftsmanship",
        "Legal Status": "Lawful",
        "Ethical Stance": "Traditionalist",
        "Historical Background": "Ancient Order of Craftsmen",
        "Public Relations": "Proud and Exclusive",
        "Economic Activities": ["Crafting", "Artisan Training"],
        "Cultural Impact": "Keeper of Traditions"
    },
    "Revolutionary_Front": {
        "Name": "Revolutionary Front",
        "Type": "Rebel Group",
        "Size": "Growing",
        "Influence": "Increasing",
        "Reputation": "Revolutionary",
        "Leadership": "Charismatic Leader",
        "Economic Power": "Rising",
        "Military Strength": "Guerrilla",
        "Goals/Objectives": "Overthrow Oppressive Regimes",
        "Alliances": ["Oppressed Populations"],
        "Rivalries": ["Authoritarian Governments"],
        "Operational Area": "Conflict Zones",
        "Membership": "Diverse",
        "Special Capabilities": "Guerrilla Warfare",
        "Legal Status": "Outlawed",
        "Ethical Stance": "Ideological",
        "Historical Background": "Formed in Response to Tyranny",
        "Public Relations": "Mixed, Heroic to Some, Villains to Others",
        "Economic Activities": ["Fundraising", "Propaganda"],
        "Cultural Impact": "Symbol of Resistance"
    }
}

