pirates = {
    "Captain_Redbeard": {
        "Name": "Captain Redbeard",
        "Ship Name": "Crimson Raider",
        "Reputation": "Feared",
        "Strength": "High",
        "Aggressiveness": "High",
        "Preferred Targets": ["Cargo Ships", "Unarmed Vessels"],
        "Area of Operation": "Outer Rim",
        "Tactics": "Ambush",
        "Notoriety": "Very High",
        "Wealth": "Rich",
        "Crew Size": 50,
        "Ship Type": "Corvette",
        "Technology Level": "Moderate",
        "Bounty": 50000,
        "Allegiances": ["None"],
        "Stealth Capabilities": "Moderate",
        "Resourcefulness": "High",
        "Morality": "Low",
        "Backstory": "Former navy officer turned rogue",
        "Current Goals": "Amass a pirate fleet"
    },
    "Blackstar_Syndicate": {
        "Name": "Blackstar Syndicate",
        "Ship Name": "Void Stalker",
        "Reputation": "Cunning",
        "Strength": "Medium",
        "Aggressiveness": "Moderate",
        "Preferred Targets": ["Mining Vessels", "Research Ships"],
        "Area of Operation": "Asteroid Belt",
        "Tactics": "Hit-and-Run",
        "Notoriety": "High",
        "Wealth": "Moderate",
        "Crew Size": 30,
        "Ship Type": "Frigate",
        "Technology Level": "High",
        "Bounty": 30000,
        "Allegiances": ["Underworld Figures"],
        "Stealth Capabilities": "High",
        "Resourcefulness": "Moderate",
        "Morality": "Variable",
        "Backstory": "A coalition of disgruntled miners and hackers",
        "Current Goals": "Control major trade routes"
    },
    "Siren_Queen": {
        "Name": "Siren Queen",
        "Ship Name": "Nebula's Whisper",
        "Reputation": "Mysterious",
        "Strength": "Moderate",
        "Aggressiveness": "Low",
        "Preferred Targets": ["Luxury Yachts", "Treasure Ships"],
        "Area of Operation": "Trade Lanes",
        "Tactics": "Deception",
        "Notoriety": "Moderate",
        "Wealth": "Wealthy",
        "Crew Size": 20,
        "Ship Type": "Stealth Cruiser",
        "Technology Level": "Advanced",
        "Bounty": 40000,
        "Allegiances": ["Independent Merchants"],
        "Stealth Capabilities": "Very High",
        "Resourcefulness": "Very High",
        "Morality": "Medium",
        "Backstory": "A former aristocrat turned pirate",
        "Current Goals": "Seeking a legendary lost artifact"
    },
    "Scarlet_Marauder": {
        "Name": "Captain Velara 'Scarlet' Tyrax",
        "Ship Name": "Scarlet Marauder",
        "Reputation": "Infamous",
        "Strength": "High",
        "Aggressiveness": "Volatile",
        "Preferred Targets": ["Luxury Transports", "Merchant Vessels"],
        "Area of Operation": "Nebula Quadrant",
        "Tactics": "Swift and Brutal Attacks",
        "Notoriety": "Very High",
        "Wealth": "Rich from Plunder",
        "Crew Size": 40,
        "Ship Type": "Heavily Modified Cruiser",
        "Technology Level": "Advanced",
        "Bounty": 75000,
        "Allegiances": ["None", "Operates Independently"],
        "Stealth Capabilities": "Moderate",
        "Resourcefulness": "Very High",
        "Morality": "Unpredictable",
        "Backstory": "Ex-Imperial Officer turned Rogue",
        "Current Goals": "Establish Dominance in the Nebula Quadrant"
    },
    "Rift_Raider": {
        "Name": "Commander Jax 'Rift' Torren",
        "Ship Name": "Rift Raider",
        "Reputation": "Cunning",
        "Strength": "Medium",
        "Aggressiveness": "Calculated",
        "Preferred Targets": ["Research Ships", "Unarmed Explorers"],
        "Area of Operation": "Outer Rim Territories",
        "Tactics": "Ambush from Warp Jumps",
        "Notoriety": "Rising",
        "Wealth": "Growing",
        "Crew Size": 25,
        "Ship Type": "Stealth Frigate",
        "Technology Level": "High",
        "Bounty": 50000,
        "Allegiances": ["Outer Rim Pirate Syndicates"],
        "Stealth Capabilities": "High",
        "Resourcefulness": "High",
        "Morality": "Self-Serving",
        "Backstory": "Former Freelance Smuggler",
        "Current Goals": "Acquire Exotic Technologies"
    },

        "Nebula_Ghost": {
        "Name": "Captain Lyra 'Nebula Ghost' Krell",
        "Ship Name": "Phantom's Wisp",
        "Reputation": "Elusive",
        "Strength": "Moderate",
        "Aggressiveness": "Opportunistic",
        "Preferred Targets": ["Isolated Cargo Fleets", "Science Expeditions"],
        "Area of Operation": "Gas Nebulae",
        "Tactics": "Guerrilla Warfare",
        "Notoriety": "Mysterious",
        "Wealth": "Unknown",
        "Crew Size": 20,
        "Ship Type": "Light Stealth Cruiser",
        "Technology Level": "Moderate",
        "Bounty": 60000,
        "Allegiances": ["Independent", "Occasional Smuggler Ties"],
        "Stealth Capabilities": "Very High",
        "Resourcefulness": "Innovative",
        "Morality": "Gray",
        "Backstory": "Former Space Navy Recon Expert",
        "Current Goals": "Remain Untraceable while Accumulating Wealth"
    },
    "Ironclad_Reaver": {
        "Name": "Warlord Grom 'Ironclad' Hark",
        "Ship Name": "Ironclad Reaver",
        "Reputation": "Brutal",
        "Strength": "Very High",
        "Aggressiveness": "Aggressive",
        "Preferred Targets": ["Merchant Convoys", "Military Freighters"],
        "Area of Operation": "Trade Routes",
        "Tactics": "Direct Assault",
        "Notoriety": "Feared",
        "Wealth": "Plentiful",
        "Crew Size": 100,
        "Ship Type": "Armored Battleship",
        "Technology Level": "Low",
        "Bounty": 80000,
        "Allegiances": ["Pirate Warbands"],
        "Stealth Capabilities": "Low",
        "Resourcefulness": "Moderate",
        "Morality": "Ruthless",
        "Backstory": "Ascended from a Pirate Footsoldier",
        "Current Goals": "Expand Territory and Influence"
    },
    "Star_Serpent": {
        "Name": "Mistress Syl 'Star Serpent' Vara",
        "Ship Name": "Serpent's Grasp",
        "Reputation": "Seductive and Deadly",
        "Strength": "Medium",
        "Aggressiveness": "Strategic",
        "Preferred Targets": ["High-value Transports", "Luxury Vessels"],
        "Area of Operation": "Core Systems",
        "Tactics": "Deception and Speed",
        "Notoriety": "Infamous",
        "Wealth": "Extravagant",
        "Crew Size": 15,
        "Ship Type": "Fast Attack Corvette",
        "Technology Level": "High",
        "Bounty": 70000,
        "Allegiances": ["Select Pirate Circles", "Black Market Contacts"],
        "Stealth Capabilities": "High",
        "Resourcefulness": "High",
        "Morality": "Manipulative",
        "Backstory": "Former Aristocrat Turned Renegade",
        "Current Goals": "Amass a Fortune and a Reputation"
    }
}

