pirates = {
    "Captain_Redbeard": {
        "Name": "Captain Redbeard",
        "Ship Name": "Crimson Raider",
        "Reputation": "Feared",
        "Strength": "High",
        "Aggressiveness": "High",
        "Preferred Targets": ["Cargo Ships", "Unarmed Vessels"],
        "Area of Operation": "Outer Rim",
        "Tactics": "Ambush",
        "Notoriety": "Very High",
        "Wealth": "Rich",
        "Crew Size": 50,
        "Ship Type": "Corvette",
        "Technology Level": "Moderate",
        "Bounty": 50000,
        "Allegiances": ["None"],
        "Stealth Capabilities": "Moderate",
        "Resourcefulness": "High",
        "Morality": "Low",
        "Backstory": "Former navy officer turned rogue",
        "Current Goals": "Amass a pirate fleet"
    },
    "Blackstar_Syndicate": {
        "Name": "Blackstar Syndicate",
        "Ship Name": "Void Stalker",
        "Reputation": "Cunning",
        "Strength": "Medium",
        "Aggressiveness": "Moderate",
        "Preferred Targets": ["Mining Vessels", "Research Ships"],
        "Area of Operation": "Asteroid Belt",
        "Tactics": "Hit-and-Run",
        "Notoriety": "High",
        "Wealth": "Moderate",
        "Crew Size": 30,
        "Ship Type": "Frigate",
        "Technology Level": "High",
        "Bounty": 30000,
        "Allegiances": ["Underworld Figures"],
        "Stealth Capabilities": "High",
        "Resourcefulness": "Moderate",
        "Morality": "Variable",
        "Backstory": "A coalition of disgruntled miners and hackers",
        "Current Goals": "Control major trade routes"
    },
    "Siren_Queen": {
        "Name": "Siren Queen",
        "Ship Name": "Nebula's Whisper",
        "Reputation": "Mysterious",
        "Strength": "Moderate",
        "Aggressiveness": "Low",
        "Preferred Targets": ["Luxury Yachts", "Treasure Ships"],
        "Area of Operation": "Trade Lanes",
        "Tactics": "Deception",
        "Notoriety": "Moderate",
        "Wealth": "Wealthy",
        "Crew Size": 20,
        "Ship Type": "Stealth Cruiser",
        "Technology Level": "Advanced",
        "Bounty": 40000,
        "Allegiances": ["Independent Merchants"],
        "Stealth Capabilities": "Very High",
        "Resourcefulness": "Very High",
        "Morality": "Medium",
        "Backstory": "A former aristocrat turned pirate",
        "Current Goals": "Seeking a legendary lost artifact"
    }
}
