planets = {
    "TerraNova": {
        "Name": "TerraNova", 
        "Type": "Habitable", 
        "Size": "Medium", 
        "Population": "High", 
        "Government Type": "Democracy", 
        "Economic Status": "Wealthy", 
        "Technological Level": "Advanced", 
        "Resource Abundance": "Moderate", 
        "Cultural Characteristics": "Diverse", 
        "Stability": "Stable", 
        "Climate": "Temperate", 
        "Strategic Importance": "High", 
        "Trade Regulations": "Moderate", 
        "Black Market Activity": "Low", 
        "Spaceport Facilities": "Excellent", 
        "Alliances and Conflicts": "Neutral",
        "Historical Significance": "High", 
        "Orbital Position": "Inner System", 
        "Special Conditions": "None", 
        "Local Customs": "Varied", 
        "Location": {"X": 100, "Y": 200, "Z": 300}
        },
    "Zypherus": {"Name": "Zypherus", "Type": "Gas Giant", "Size": "Large", "Population": "Low", "Government Type": "Corporate State", "Economic Status": "Developing", "Technological Level": "Medium", "Resource Abundance": "High", "Cultural Characteristics": "Industrial", "Stability": "Volatile", "Climate": "Gas Storms", "Strategic Importance": "Medium", "Trade Regulations": "Low", "Black Market Activity": "High", "Spaceport Facilities": "Basic", "Alliances and Conflicts": "Conflicted", "Historical Significance": "Low", "Orbital Position": "Outer System", "Special Conditions": "Hazardous Atmosphere", "Local Customs": "Strict", "Location": {"X": -500, "Y": 150, "Z": 450}},
    "IcarusV": {
        "Name": "IcarusV",
        "Type": "Desert Planet",
        "Size": "Small",
        "Population": "Medium",
        "Government Type": "Oligarchy",
        "Economic Status": "Rich",
        "Technological Level": "High",
        "Resource Abundance": "Scarce",
        "Cultural Characteristics": "Warrior Code",
        "Stability": "Unstable",
        "Climate": "Arid",
        "Strategic Importance": "Medium",
        "Trade Regulations": "Strict",
        "Black Market Activity": "Moderate",
        "Spaceport Facilities": "Advanced",
        "Alliances and Conflicts": "Isolated",
        "Historical Significance": "Medium",
        "Orbital Position": "Outer System",
        "Special Conditions": "Rare Minerals",
        "Local Customs": "Honor-based",
        "Location": {"X": 350, "Y": -100, "Z": 75}
    },
    "Nebulon": {
        "Name": "Nebulon",
        "Type": "Oceanic",
        "Size": "Large",
        "Population": "Sparse",
        "Government Type": "Anarchy",
        "Economic Status": "Poor",
        "Technological Level": "Low",
        "Resource Abundance": "Abundant",
        "Cultural Characteristics": "Mystical",
        "Stability": "Chaotic",
        "Climate": "Temperate",
        "Strategic Importance": "Low",
        "Trade Regulations": "None",
        "Black Market Activity": "High",
        "Spaceport Facilities": "Rudimentary",
        "Alliances and Conflicts": "Neutral",
        "Historical Significance": "Ancient Ruins",
        "Orbital Position": "Mid System",
        "Special Conditions": "Underwater Cities",
        "Local Customs": "Pacifist",
        "Location": {"X": -220, "Y": 340, "Z": 90}
    },
    "Talara IV": {
        "Name": "Talara IV",
        "Type": "Oceanic",
        "Size": "Medium",
        "Population": "Sparse",
        "Government Type": "Tribal Councils",
        "Economic Status": "Developing",
        "Technological Level": "Low",
        "Resource Abundance": "Rich in Marine Life",
        "Cultural Characteristics": "Strong Maritime Traditions",
        "Stability": "Stable",
        "Climate": "Tropical",
        "Strategic Importance": "Low",
        "Trade Regulations": "Moderate",
        "Black Market Activity": "Low",
        "Spaceport Facilities": "Basic",
        "Alliances and Conflicts": "Isolated",
        "Historical Significance": "Ancient Sea-Faring Culture",
        "Orbital Position": "Mid System",
        "Special Conditions": "Vast Oceans with Small Archipelagos",
        "Local Customs": "Respect for Sea Life",
        "Location": {"X": 200, "Y": 300, "Z": -150}
    },
    "Vega Prime": {
        "Name": "Vega Prime",
        "Type": "Desert",
        "Size": "Large",
        "Population": "Moderate",
        "Government Type": "Corporate Governance",
        "Economic Status": "Wealthy",
        "Technological Level": "Advanced",
        "Resource Abundance": "Mineral Rich",
        "Cultural Characteristics": "Corporate Efficiency",
        "Stability": "High",
        "Climate": "Arid",
        "Strategic Importance": "High",
        "Trade Regulations": "Strict",
        "Black Market Activity": "Moderate",
        "Spaceport Facilities": "Advanced",
        "Alliances and Conflicts": "Corporate Rivalries",
        "Historical Significance": "Center of Mining Operations",
        "Orbital Position": "Outer System",
        "Special Conditions": "Extensive Mining Networks",
        "Local Customs": "Business First Approach",
        "Location": {"X": -400, "Y": 50, "Z": 100}
    },
        "Zephyrion": {
        "Name": "Zephyrion",
        "Type": "Gas Giant",
        "Size": "Huge",
        "Population": "Mining Colonies",
        "Government Type": "Corporate",
        "Economic Status": "Resource-Driven",
        "Technological Level": "Moderate",
        "Resource Abundance": "Helium-3, Hydrogen",
        "Cultural Characteristics": "Industrial",
        "Stability": "Economically Stable",
        "Climate": "Atmospheric Storms",
        "Strategic Importance": "Energy Production",
        "Trade Regulations": "High",
        "Black Market Activity": "Low",
        "Spaceport Facilities": "Orbital Platforms",
        "Alliances and Conflicts": "Corporate Alliances",
        "Historical Significance": "Major Fuel Source",
        "Orbital Position": "Outer System",
        "Special Conditions": "Gas Harvesting Operations",
        "Local Customs": "Worker Communities",
        "Location": {"X": 320, "Y": 140, "Z": -210}
    },
    "Arcadia": {
        "Name": "Arcadia",
        "Type": "Forest World",
        "Size": "Medium",
        "Population": "Low",
        "Government Type": "Eco-Governance",
        "Economic Status": "Sustainable",
        "Technological Level": "Eco-friendly Tech",
        "Resource Abundance": "Bio-Diverse Flora and Fauna",
        "Cultural Characteristics": "Nature-Centric",
        "Stability": "Peaceful",
        "Climate": "Temperate",
        "Strategic Importance": "Biological Research",
        "Trade Regulations": "Environmental Protection Laws",
        "Black Market Activity": "Poaching Threats",
        "Spaceport Facilities": "Minimalist",
        "Alliances and Conflicts": "Environmental Advocacy",
        "Historical Significance": "Biodiversity Reserve",
        "Orbital Position": "Mid System",
        "Special Conditions": "Wildlife Sanctuaries",
        "Local Customs": "Conservation Rituals",
        "Location": {"X": -100, "Y": 255, "Z": 85}
    },
        "Iridia": {
        "Name": "Iridia",
        "Type": "Urbanized Planet",
        "Size": "Small",
        "Population": "Densely Populated",
        "Government Type": "Federation",
        "Economic Status": "Trade Hub",
        "Technological Level": "High",
        "Resource Abundance": "Imported Resources",
        "Cultural Characteristics": "Melting Pot of Cultures",
        "Stability": "Politically Stable",
        "Climate": "Controlled Environment",
        "Strategic Importance": "Central Trading Hub",
        "Trade Regulations": "Complex",
        "Black Market Activity": "Prevalent",
        "Spaceport Facilities": "Extensive",
        "Alliances and Conflicts": "Numerous Political Alliances",
        "Historical Significance": "Site of Major Intergalactic Treaties",
        "Orbital Position": "Inner System",
        "Special Conditions": "High-tech Urban Landscape",
        "Local Customs": "Cosmopolitan Lifestyle",
        "Location": {"X": 500, "Y": -300, "Z": 100}
    },
    "Krynn": {
        "Name": "Krynn",
        "Type": "Frozen Tundra",
        "Size": "Medium",
        "Population": "Scattered Settlements",
        "Government Type": "Tribal",
        "Economic Status": "Self-Sufficient",
        "Technological Level": "Low",
        "Resource Abundance": "Rare Minerals",
        "Cultural Characteristics": "Survivalist",
        "Stability": "Isolated",
        "Climate": "Sub-Zero",
        "Strategic Importance": "Mineral Exploitation Potential",
        "Trade Regulations": "Minimal",
        "Black Market Activity": "Some Smuggling",
        "Spaceport Facilities": "Few",
        "Alliances and Conflicts": "Largely Neutral",
        "Historical Significance": "Untapped Resources",
        "Orbital Position": "Outer System",
        "Special Conditions": "Harsh Climate",
        "Local Customs": "Strong Community Bonds",
        "Location": {"X": -450, "Y": 200, "Z": -50}
    },
    "Erebus": {
        "Name": "Erebus",
        "Type": "Volcanic",
        "Size": "Large",
        "Population": "Mining Colonies",
        "Government Type": "Corporate",
        "Economic Status": "Resource-Driven",
        "Technological Level": "Moderate",
        "Resource Abundance": "Precious Metals",
        "Cultural Characteristics": "Industrial",
        "Stability": "Company Controlled",
        "Climate": "Extreme Heat",
        "Strategic Importance": "Unique Minerals",
        "Trade Regulations": "Corporate Law",
        "Black Market Activity": "High Risk",
        "Spaceport Facilities": "Industrial",
        "Alliances and Conflicts": "Corporate Rivalries",
        "Historical Significance": "Newly Discovered",
        "Orbital Position": "Outer Rim",
        "Special Conditions": "Active Volcanoes",
        "Local Customs": "Miner Traditions",
        "Location": {"X": 75, "Y": -575, "Z": 220}
    },
    "Celestia": {
        "Name": "Celestia",
        "Type": "Cloud City",
        "Size": "Floating Cities",
        "Population": "Moderate",
        "Government Type": "Oligarchy",
        "Economic Status": "Luxury Tourism",
        "Technological Level": "High",
        "Resource Abundance": "Artificially Sustained",
        "Cultural Characteristics": "Elitist",
        "Stability": "Socially Stratified",
        "Climate": "Artificial Atmosphere",
        "Strategic Importance": "Tourist Destination",
        "Trade Regulations": "Strict",
        "Black Market Activity": "Discreet",
        "Spaceport Facilities": "Premium",
        "Alliances and Conflicts": "Elite Networks",
        "Historical Significance": "Symbol of Luxury",
        "Orbital Position": "High Orbit",
        "Special Conditions": "Zero-Gravity Areas",
        "Local Customs": "High Society Etiquette",
        "Location": {"X": 300, "Y": 100, "Z": -400}
    },
      "Avalon": {
        "Name": "Avalon",
        "Type": "Temperate Paradise",
        "Size": "Medium",
        "Population": "Diverse",
        "Government Type": "Democratic",
        "Economic Status": "Balanced",
        "Technological Level": "Moderate",
        "Resource Abundance": "Rich Biodiversity",
        "Cultural Characteristics": "Harmonious",
        "Stability": "Peaceful",
        "Climate": "Ideal",
        "Strategic Importance": "Ecological Haven",
        "Trade Regulations": "Eco-Friendly",
        "Black Market Activity": "Low",
        "Spaceport Facilities": "Eco-Integrated",
        "Alliances and Conflicts": "Environmental Advocates",
        "Historical Significance": "Conservation Efforts",
        "Orbital Position": "Mid System",
        "Special Conditions": "Wildlife Reserves",
        "Local Customs": "Nature Celebrations",
        "Location": {"X": -200, "Y": 350, "Z": 75}
    }
       

}


