planets_data = {
    "terranova": {
        "name": "terranova", 
        "type": "habitable", 
        "size": "medium", 
        "population": "high", 
        "government_type": "democracy", 
        "economic_status": "wealthy", 
        "technological_level": "advanced", 
        "resource_abundance": "moderate", 
        "cultural_characteristics": "diverse", 
        "stability": "stable", 
        "climate": "temperate", 
        "strategic_importance": "high", 
        "trade_regulations": "moderate", 
        "black_market_activity": "low", 
        "spaceport_facilities": "excellent", 
        "alliances_and_conflicts": "neutral",
        "historical_significance": "high", 
        "orbital_position": "inner system", 
        "special_conditions": "none", 
        "local_customs": "varied", 
        "location": {"x": 100, "y": 200, "z": 300}
        },
    "zypherus": {"name": "zypherus", "type": "gas giant", "size": "large", "population": "low", "government_type": "corporate state", "economic_status": "developing", "technological_level": "medium", "resource_abundance": "high", "cultural_characteristics": "industrial", "stability": "volatile", "climate": "gas storms", "strategic_importance": "medium", "trade_regulations": "low", "black_market_activity": "high", "spaceport_facilities": "basic", "alliances_and_conflicts": "conflicted", "historical_significance": "low", "orbital_position": "outer system", "special_conditions": "hazardous atmosphere", "local_customs": "strict", "location": {"x": -500, "y": 150, "z": 450}},
    "icarusv": {
        "name": "icarusv",
        "type": "desert planet",
        "size": "small",
        "population": "medium",
        "government_type": "oligarchy",
        "economic_status": "rich",
        "technological_level": "high",
        "resource_abundance": "scarce",
        "cultural_characteristics": "warrior code",
        "stability": "unstable",
        "climate": "arid",
        "strategic_importance": "medium",
        "trade_regulations": "strict",
        "black_market_activity": "moderate",
        "spaceport_facilities": "advanced",
        "alliances_and_conflicts": "isolated",
        "historical_significance": "medium",
        "orbital_position": "outer system",
        "special_conditions": "rare minerals",
        "local_customs": "honor-based",
        "location": {"x": 350, "y": -100, "z": 75}
    },
    "nebulon": {
        "name": "nebulon",
        "type": "oceanic",
        "size": "large",
        "population": "sparse",
        "government_type": "anarchy",
        "economic_status": "poor",
        "technological_level": "low",
        "resource_abundance": "abundant",
        "cultural_characteristics": "mystical",
        "stability": "chaotic",
        "climate": "temperate",
        "strategic_importance": "low",
        "trade_regulations": "none",
        "black_market_activity": "high",
        "spaceport_facilities": "rudimentary",
        "alliances_and_conflicts": "neutral",
        "historical_significance": "ancient ruins",
        "orbital_position": "mid system",
        "special_conditions": "underwater cities",
        "local_customs": "pacifist",
        "location": {"x": -220, "y": 340, "z": 90}
    },
    "talara iv": {
        "name": "talara iv",
        "type": "oceanic",
        "size": "medium",
        "population": "sparse",
        "government_type": "tribal councils",
        "economic_status": "developing",
        "technological_level": "low",
        "resource_abundance": "rich in marine life",
        "cultural_characteristics": "strong maritime traditions",
        "stability": "stable",
        "climate": "tropical",
        "strategic_importance": "low",
        "trade_regulations": "moderate",
        "black_market_activity": "low",
        "spaceport_facilities": "basic",
        "alliances_and_conflicts": "isolated",
        "historical_significance": "ancient sea-faring culture",
        "orbital_position": "mid system",
        "special_conditions": "vast oceans with small archipelagos",
        "local_customs": "respect for sea life",
        "location": {"x": 200, "y": 300, "z": -150}
    },
    "vega prime": {
        "name": "vega prime",
        "type": "desert",
        "size": "large",
        "population": "moderate",
        "government_type": "corporate governance",
        "economic_status": "wealthy",
        "technological_level": "advanced",
        "resource_abundance": "mineral rich",
        "cultural_characteristics": "corporate efficiency",
        "stability": "high",
        "climate": "arid",
        "strategic_importance": "high",
        "trade_regulations": "strict",
        "black_market_activity": "moderate",
        "spaceport_facilities": "advanced",
        "alliances_and_conflicts": "corporate rivalries",
        "historical_significance": "center of mining operations",
        "orbital_position": "outer system",
        "special_conditions": "extensive mining networks",
        "local_customs": "business first approach",
        "location": {"x": -400, "y": 50, "z": 100}
    },
        "zephyrion": {
        "name": "zephyrion",
        "type": "gas giant",
        "size": "huge",
        "population": "mining colonies",
        "government_type": "corporate",
        "economic_status": "resource-driven",
        "technological_level": "moderate",
        "resource_abundance": "helium-3, hydrogen",
        "cultural_characteristics": "industrial",
        "stability": "economically stable",
        "climate": "atmospheric storms",
        "strategic_importance": "energy production",
        "trade_regulations": "high",
        "black_market_activity": "low",
        "spaceport_facilities": "orbital platforms",
        "alliances_and_conflicts": "corporate alliances",
        "historical_significance": "major fuel source",
        "orbital_position": "outer system",
        "special_conditions": "gas harvesting operations",
        "local_customs": "worker communities",
        "location": {"x": 320, "y": 140, "z": -210}
    },
    "arcadia": {
        "name": "arcadia",
        "type": "forest world",
        "size": "medium",
        "population": "low",
        "government_type": "eco-governance",
        "economic_status": "sustainable",
        "technological_level": "eco-friendly tech",
        "resource_abundance": "bio-diverse flora and fauna",
        "cultural_characteristics": "nature-centric",
        "stability": "peaceful",
        "climate": "temperate",
        "strategic_importance": "biological research",
        "trade_regulations": "environmental protection laws",
        "black_market_activity": "poaching threats",
        "spaceport_facilities": "minimalist",
        "alliances_and_conflicts": "environmental advocacy",
        "historical_significance": "biodiversity reserve",
        "orbital_position": "mid system",
        "special_conditions": "wildlife sanctuaries",
        "local_customs": "conservation rituals",
        "location": {"x": -100, "y": 255, "z": 85}
    },
        "iridia": {
        "name": "iridia",
        "type": "urbanized planet",
        "size": "small",
        "population": "densely populated",
        "government_type": "federation",
        "economic_status": "trade hub",
        "technological_level": "high",
        "resource_abundance": "imported resources",
        "cultural_characteristics": "melting pot of cultures",
        "stability": "politically stable",
        "climate": "controlled environment",
        "strategic_importance": "central trading hub",
        "trade_regulations": "complex",
        "black_market_activity": "prevalent",
        "spaceport_facilities": "extensive",
        "alliances_and_conflicts": "numerous political alliances",
        "historical_significance": "site of major intergalactic treaties",
        "orbital_position": "inner system",
        "special_conditions": "high-tech urban landscape",
        "local_customs": "cosmopolitan lifestyle",
        "location": {"x": 500, "y": -300, "z": 100}
    },
    "krynn": {
        "name": "krynn",
        "type": "frozen tundra",
        "size": "medium",
        "population": "scattered settlements",
        "government_type": "tribal",
        "economic_status": "self-sufficient",
        "technological_level": "low",
        "resource_abundance": "rare minerals",
        "cultural_characteristics": "survivalist",
        "stability": "isolated",
        "climate": "sub-zero",
        "strategic_importance": "mineral exploitation potential",
        "trade_regulations": "minimal",
        "black_market_activity": "some smuggling",
        "spaceport_facilities": "few",
        "alliances_and_conflicts": "largely neutral",
        "historical_significance": "untapped resources",
        "orbital_position": "outer system",
        "special_conditions": "harsh climate",
        "local_customs": "strong community bonds",
        "location": {"x": -450, "y": 200, "z": -50}
    },
    "erebus": {
        "name": "erebus",
        "type": "volcanic",
        "size": "large",
        "population": "mining colonies",
        "government_type": "corporate",
        "economic_status": "resource-driven",
        "technological_level": "moderate",
        "resource_abundance": "precious metals",
        "cultural_characteristics": "industrial",
        "stability": "company controlled",
        "climate": "extreme heat",
        "strategic_importance": "unique minerals",
        "trade_regulations": "corporate law",
        "black_market_activity": "high risk",
        "spaceport_facilities": "industrial",
        "alliances_and_conflicts": "corporate rivalries",
        "historical_significance": "newly discovered",
        "orbital_position": "outer rim",
        "special_conditions": "active volcanoes",
        "local_customs": "miner traditions",
        "location": {"x": 75, "y": -575, "z": 220}
    },
    "celestia": {
        "name": "celestia",
        "type": "cloud city",
        "size": "floating cities",
        "population": "moderate",
        "government_type": "oligarchy",
        "economic_status": "luxury tourism",
        "technological_level": "high",
        "resource_abundance": "artificially sustained",
        "cultural_characteristics": "elitist",
        "stability": "socially stratified",
        "climate": "artificial atmosphere",
        "strategic_importance": "tourist destination",
        "trade_regulations": "strict",
        "black_market_activity": "discreet",
        "spaceport_facilities": "premium",
        "alliances_and_conflicts": "elite networks",
        "historical_significance": "symbol of luxury",
        "orbital_position": "high orbit",
        "special_conditions": "zero-gravity areas",
        "local_customs": "high society etiquette",
        "location": {"x": 300, "y": 100, "z": -400}
    },
      "avalon": {
        "name": "avalon",
        "type": "temperate paradise",
        "size": "medium",
        "population": "diverse",
        "government_type": "democratic",
        "economic_status": "balanced",
        "technological_level": "moderate",
        "resource_abundance": "rich biodiversity",
        "cultural_characteristics": "harmonious",
        "stability": "peaceful",
        "climate": "ideal",
        "strategic_importance": "ecological haven",
        "trade_regulations": "eco-friendly",
        "black_market_activity": "low",
        "spaceport_facilities": "eco-integrated",
        "alliances_and_conflicts": "environmental advocates",
        "historical_significance": "conservation efforts",
        "orbital_position": "mid system",
        "special_conditions": "wildlife reserves",
        "local_customs": "nature celebrations",
        "location": {"x": -200, "y": 350, "z": 75}
    }
}


