planets = {
    "TerraNova": {"Name": "TerraNova", "Type": "Habitable", "Size": "Medium", "Population": "High", "Government Type": "Democracy", "Economic Status": "Wealthy", "Technological Level": "Advanced", "Resource Abundance": "Moderate", "Cultural Characteristics": "Diverse", "Stability": "Stable", "Climate": "Temperate", "Strategic Importance": "High", "Trade Regulations": "Moderate", "Black Market Activity": "Low", "Spaceport Facilities": "Excellent", "Alliances and Conflicts": "Neutral", "Historical Significance": "High", "Orbital Position": "Inner System", "Special Conditions": "None", "Local Customs": "Varied", "Location": {"X": 100, "Y": 200, "Z": 300}},
    "Zypherus": {"Name": "Zypherus", "Type": "Gas Giant", "Size": "Large", "Population": "Low", "Government Type": "Corporate State", "Economic Status": "Developing", "Technological Level": "Medium", "Resource Abundance": "High", "Cultural Characteristics": "Industrial", "Stability": "Volatile", "Climate": "Gas Storms", "Strategic Importance": "Medium", "Trade Regulations": "Low", "Black Market Activity": "High", "Spaceport Facilities": "Basic", "Alliances and Conflicts": "Conflicted", "Historical Significance": "Low", "Orbital Position": "Outer System", "Special Conditions": "Hazardous Atmosphere", "Local Customs": "Strict", "Location": {"X": -500, "Y": 150, "Z": 450}},
    "IcarusV": {
        "Name": "IcarusV",
        "Type": "Desert Planet",
        "Size": "Small",
        "Population": "Medium",
        "Government Type": "Oligarchy",
        "Economic Status": "Rich",
        "Technological Level": "High",
        "Resource Abundance": "Scarce",
        "Cultural Characteristics": "Warrior Code",
        "Stability": "Unstable",
        "Climate": "Arid",
        "Strategic Importance": "Medium",
        "Trade Regulations": "Strict",
        "Black Market Activity": "Moderate",
        "Spaceport Facilities": "Advanced",
        "Alliances and Conflicts": "Isolated",
        "Historical Significance": "Medium",
        "Orbital Position": "Outer System",
        "Special Conditions": "Rare Minerals",
        "Local Customs": "Honor-based",
        "Location": {"X": 350, "Y": -100, "Z": 75}
    },
    "Nebulon": {
        "Name": "Nebulon",
        "Type": "Oceanic",
        "Size": "Large",
        "Population": "Sparse",
        "Government Type": "Anarchy",
        "Economic Status": "Poor",
        "Technological Level": "Low",
        "Resource Abundance": "Abundant",
        "Cultural Characteristics": "Mystical",
        "Stability": "Chaotic",
        "Climate": "Temperate",
        "Strategic Importance": "Low",
        "Trade Regulations": "None",
        "Black Market Activity": "High",
        "Spaceport Facilities": "Rudimentary",
        "Alliances and Conflicts": "Neutral",
        "Historical Significance": "Ancient Ruins",
        "Orbital Position": "Mid System",
        "Special Conditions": "Underwater Cities",
        "Local Customs": "Pacifist",
        "Location": {"X": -220, "Y": 340, "Z": 90}
    }
}
