ship_classes = {
    "Freighter": {
        "Type": "Cargo",
        "Size": "Large",
        "Speed": "Slow",
        "Cargo Capacity": 1000,
        "Crew Capacity": 30,
        "Weaponry": "Light",
        "Defense Systems": "Moderate",
        "Fuel Efficiency": "Low",
        "Maneuverability": "Poor",
        "Range": "Long",
        "Tech Level": "Medium",
        "Condition": "Sturdy",
        "Upgrade Capacity": "High",
        "Stealth Capabilities": "None",
        "Docking Compatibility": "Standard",
        "Communication Systems": "Standard",
        "Life Support Systems": "High",
        "Sensor Array": "Basic",
        "AI and Automation Level": "Moderate"
    },
    "Fighter": {
        "Type": "Combat",
        "Size": "Small",
        "Speed": "Fast",
        "Cargo Capacity": 50,
        "Crew Capacity": 1,
        "Weaponry": "Heavy",
        "Defense Systems": "High",
        "Fuel Efficiency": "Moderate",
        "Maneuverability": "High",
        "Range": "Short",
        "Tech Level": "High",
        "Condition": "Agile",
        "Upgrade Capacity": "Moderate",
        "Stealth Capabilities": "Low",
        "Docking Compatibility": "Versatile",
        "Communication Systems": "Advanced",
        "Life Support Systems": "Basic",
        "Sensor Array": "Advanced",
        "AI and Automation Level": "Low"
    },
    "Explorer": {
        "Type": "Scout/Research",
        "Size": "Medium",
        "Speed": "Moderate",
        "Cargo Capacity": 200,
        "Crew Capacity": 15,
        "Weaponry": "Light",
        "Defense Systems": "Moderate",
        "Fuel Efficiency": "High",
        "Maneuverability": "High",
        "Range": "Very Long",
        "Tech Level": "Advanced",
        "Condition": "New",
        "Upgrade Capacity": "High",
        "Stealth Capabilities": "Moderate",
        "Docking Compatibility": "Standard",
        "Communication Systems": "Advanced",
        "Life Support Systems": "Enhanced",
        "Sensor Array": "Superior",
        "AI and Automation Level": "High"
    },
    "Diplomat": {
        "Type": "Passenger",
        "Size": "Medium",
        "Speed": "Moderate",
        "Cargo Capacity": 100,
        "Crew Capacity": 20,
        "Weaponry": "Minimal",
        "Defense Systems": "High",
        "Fuel Efficiency": "Moderate",
        "Maneuverability": "Medium",
        "Range": "Moderate",
        "Tech Level": "High",
        "Condition": "Pristine",
        "Upgrade Capacity": "Low",
        "Stealth Capabilities": "Low",
        "Docking Compatibility": "Universal",
        "Communication Systems": "State-of-the-Art",
        "Life Support Systems": "Luxury",
        "Sensor Array": "Advanced",
        "AI and Automation Level": "Moderate"
    },
    "Colony Ship": {
        "Type": "Transport",
        "Size": "Very Large",
        "Speed": "Slow",
        "Cargo Capacity": 2000,
        "Crew Capacity": 500,
        "Weaponry": "Moderate",
        "Defense Systems": "High",
        "Fuel Efficiency": "Low",
        "Maneuverability": "Very Poor",
        "Range": "Long",
        "Tech Level": "Medium",
        "Condition": "Sturdy",
        "Upgrade Capacity": "Moderate",
        "Stealth Capabilities": "None",
        "Docking Compatibility": "Limited",
        "Communication Systems": "Standard",
        "Life Support Systems": "Massive",
        "Sensor Array": "Basic",
        "AI and Automation Level": "Low"
    },
    "Interceptor": {
        "Type": "Combat",
        "Size": "Small",
        "Speed": "Very Fast",
        "Cargo Capacity": 20,
        "Crew Capacity": 2,
        "Weaponry": "Medium",
        "Defense Systems": "Light",
        "Fuel Efficiency": "High",
        "Maneuverability": "Very High",
        "Range": "Medium",
        "Tech Level": "High",
        "Condition": "Agile and Responsive",
        "Upgrade Capacity": "Limited",
        "Stealth Capabilities": "Moderate",
        "Docking Compatibility": "Widespread",
        "Communication Systems": "Standard",
        "Life Support Systems": "Basic",
        "Sensor Array": "Advanced",
        "AI and Automation Level": "Moderate"
    },
    "Carrier": {
        "Type": "Support",
        "Size": "Very Large",
        "Speed": "Slow",
        "Cargo Capacity": 2000,
        "Crew Capacity": 500,
        "Weaponry": "Heavy",
        "Defense Systems": "Very High",
        "Fuel Efficiency": "Low",
        "Maneuverability": "Poor",
        "Range": "Long",
        "Tech Level": "Medium",
        "Condition": "Sturdy",
        "Upgrade Capacity": "High",
        "Stealth Capabilities": "None",
        "Docking Compatibility": "Specialized",
        "Communication Systems": "Advanced",
        "Life Support Systems": "Extensive",
        "Sensor Array": "Standard",
        "AI and Automation Level": "Low"
    },
    "Stealth_Corvette": {
        "Type": "Stealth",
        "Size": "Medium",
        "Speed": "Fast",
        "Cargo Capacity": 50,
        "Crew Capacity": 10,
        "Weaponry": "Light",
        "Defense Systems": "Moderate",
        "Fuel Efficiency": "High",
        "Maneuverability": "High",
        "Range": "Long",
        "Tech Level": "Advanced",
        "Condition": "Stealth and Precision",
        "Upgrade Capacity": "Moderate",
        "Stealth Capabilities": "Very High",
        "Docking Compatibility": "Selective",
        "Communication Systems": "Encrypted",
        "Life Support Systems": "Standard",
        "Sensor Array": "Enhanced",
        "AI and Automation Level": "Moderate"
    },
    "Science_Vessel": {
        "Type": "Research",
        "Size": "Medium",
        "Speed": "Moderate",
        "Cargo Capacity": 100,
        "Crew Capacity": 30,
        "Weaponry": "Defensive",
        "Defense Systems": "Moderate",
        "Fuel Efficiency": "Moderate",
        "Maneuverability": "Medium",
        "Range": "Extended",
        "Tech Level": "High",
        "Condition": "Equipped for Long Voyages",
        "Upgrade Capacity": "High",
        "Stealth Capabilities": "Low",
        "Docking Compatibility": "Universal",
        "Communication Systems": "Advanced",
        "Life Support Systems": "Advanced",
        "Sensor Array": "State-of-the-Art",
        "AI and Automation Level": "High"
    }
}
