space_stations = {
    "Atlas_Trade_Hub": {
        "Name": "Atlas Trade Hub",
        "Type": "Trading Hub",
        "Size": "Large",
        "Population": "High",
        "Defense Capability": "Moderate",
        "Economic Status": "Wealthy",
        "Location": {"X": 450, "Y": 220, "Z": 130},
        "Facilities": ["Trade Market", "Refueling", "Repair Docks"],
        "Governance": "Corporate",
        "Tech Level": "High",
        "Security Level": "High",
        "Cultural Significance": "Moderate",
        "Trade Regulations": "Standard",
        "Access Restrictions": "None",
        "Research Opportunities": "Limited",
        "Strategic Importance": "Very High",
        "Health and Medical Facilities": "Advanced",
        "Entertainment and Leisure": ["Bars", "Restaurants", "Shopping Centers"],
        "Docking Capacity": "100 Ships",
        "Affiliation": "Neutral"
    },
    "Falcon_Military_Outpost": {
        "Name": "Falcon Military Outpost",
        "Type": "Military Outpost",
        "Size": "Medium",
        "Population": "Moderate",
        "Defense Capability": "High",
        "Economic Status": "Moderate",
        "Location": {"X": -320, "Y": 150, "Z": 75},
        "Facilities": ["Armory", "Barracks", "Tactical Command Center"],
        "Governance": "Military",
        "Tech Level": "Advanced",
        "Security Level": "Very High",
        "Cultural Significance": "Low",
        "Trade Regulations": "Strict",
        "Access Restrictions": "High",
        "Research Opportunities": "None",
        "Strategic Importance": "High",
        "Health and Medical Facilities": "Military Grade",
        "Entertainment and Leisure": ["Officer's Club"],
        "Docking Capacity": "50 Ships",
        "Affiliation": "Specific Faction"
    },
    "Zenith_Research_Facility": {
        "Name": "Zenith Research Facility",
        "Type": "Research Facility",
        "Size": "Small",
        "Population": "Low",
        "Defense Capability": "Light",
        "Economic Status": "Funded",
        "Location": {"X": 600, "Y": -100, "Z": 200},
        "Facilities": ["Laboratories", "Observatories", "Scholarly Archives"],
        "Governance": "Scientific Coalition",
        "Tech Level": "State-of-the-Art",
        "Security Level": "Moderate",
        "Cultural Significance": "High",
        "Trade Regulations": "Restricted",
        "Access Restrictions": "High",
        "Research Opportunities": "Extensive",
        "Strategic Importance": "Medium",
        "Health and Medical Facilities": "Specialized",
        "Entertainment and Leisure": ["Lecture Halls", "Galleries"],
        "Docking Capacity": "20 Ships",
        "Affiliation": "Academic"
    },
    "Orion_Refueling_Depot": {
        "Name": "Orion Refueling Depot",
        "Type": "Refueling Station",
        "Size": "Medium",
        "Population": "Moderate",
        "Defense Capability": "Moderate",
        "Economic Status": "Stable",
        "Location": {"X": -150, "Y": 250, "Z": 50},
        "Facilities": ["Fuel Reserves", "Maintenance Bays", "Supply Stores"],
        "Governance": "Corporate",
        "Tech Level": "Medium",
        "Security Level": "High",
        "Cultural Significance": "Low",
        "Trade Regulations": "Moderate",
        "Access Restrictions": "None",
        "Research Opportunities": "None",
        "Strategic Importance": "High",
        "Health and Medical Facilities": "Basic",
        "Entertainment and Leisure": ["Diners", "Recreation Rooms"],
        "Docking Capacity": "70 Ships",
        "Affiliation": "Neutral"
    },
    "Nova_Research_Platform": {
        "Name": "Nova Research Platform",
        "Type": "Research Facility",
        "Size": "Small",
        "Population": "Scientists and Researchers",
        "Defense Capability": "Light",
        "Economic Status": "Funded by Research Grants",
        "Location": {"X": 250, "Y": -75, "Z": 100},
        "Facilities": ["Advanced Laboratories", "Observation Decks", "Conference Rooms"],
        "Governance": "Scientific Board",
        "Tech Level": "High",
        "Security Level": "Moderate",
        "Cultural Significance": "Center of Scientific Advancement",
        "Trade Regulations": "Restricted to Research Materials",
        "Access Restrictions": "High",
        "Research Opportunities": "Extensive",
        "Strategic Importance": "Moderate",
        "Health and Medical Facilities": "State-of-the-Art",
        "Entertainment and Leisure": ["Scientific Exhibits", "Educational Workshops"],
        "Docking Capacity": "10 Ships",
        "Affiliation": "Independent Research Consortium"
    },
    "Driftwood_Trading_Post": {
        "Name": "Driftwood Trading Post",
        "Type": "Commercial Hub",
        "Size": "Medium",
        "Population": "Traders and Merchants",
        "Defense Capability": "Moderate",
        "Economic Status": "Busy Market",
        "Location": {"X": 560, "Y": 320, "Z": -200},
        "Facilities": ["Market Stalls", "Cargo Docks", "Trading Floors"],
        "Governance": "Merchants' Council",
        "Tech Level": "Medium",
        "Security Level": "High",
        "Cultural Significance": "Trading Crossroads",
        "Trade Regulations": "Standard Market Laws",
        "Access Restrictions": "Open to All Traders",
        "Research Opportunities": "Limited",
        "Strategic Importance": "High",
        "Health and Medical Facilities": "Basic Clinic",
        "Entertainment and Leisure": ["Bars", "Inns", "Recreational Areas"],
        "Docking Capacity": "50 Ships",
        "Affiliation": "Trade Alliances"
    },
      "Orion_Defense_Outpost": {
        "Name": "Orion Defense Outpost",
        "Type": "Military Outpost",
        "Size": "Medium",
        "Population": "Military Personnel",
        "Defense Capability": "High",
        "Economic Status": "Government Funded",
        "Location": {"X": 100, "Y": 600, "Z": -150},
        "Facilities": ["Barracks", "Weapon Systems", "Strategic Command Center"],
        "Governance": "Military Command",
        "Tech Level": "Advanced",
        "Security Level": "Very High",
        "Cultural Significance": "Strategic Military Position",
        "Trade Regulations": "Restricted Access",
        "Access Restrictions": "Military Personnel Only",
        "Research Opportunities": "Military Technology",
        "Strategic Importance": "Critical",
        "Health and Medical Facilities": "Fully Equipped Medical Center",
        "Entertainment and Leisure": ["Gyms", "Recreational Facilities"],
        "Docking Capacity": "30 Military Vessels",
        "Affiliation": "Galactic Defense Force"
    },
    "Serenity_Agricultural_Haven": {
        "Name": "Serenity Agricultural Haven",
        "Type": "Agricultural Station",
        "Size": "Large",
        "Population": "Farmers, Botanists",
        "Defense Capability": "Light",
        "Economic Status": "Agrarian",
        "Location": {"X": -300, "Y": 50, "Z": 75},
        "Facilities": ["Hydroponic Farms", "Genetic Labs", "Food Processing Units"],
        "Governance": "Agricultural Cooperative",
        "Tech Level": "Moderate",
        "Security Level": "Moderate",
        "Cultural Significance": "Provider of Sustenance",
        "Trade Regulations": "Open Trade",
        "Access Restrictions": "None",
        "Research Opportunities": "Agricultural Development",
        "Strategic Importance": "Food Supply Hub",
        "Health and Medical Facilities": "Basic Healthcare Services",
        "Entertainment and Leisure": ["Public Gardens", "Community Centers"],
        "Docking Capacity": "40 Ships",
        "Affiliation": "Independent"
    }
}


