space_stations = {
    "Atlas_Trade_Hub": {
        "Name": "Atlas Trade Hub",
        "Type": "Trading Hub",
        "Size": "Large",
        "Population": "High",
        "Defense Capability": "Moderate",
        "Economic Status": "Wealthy",
        "Location": {"X": 450, "Y": 220, "Z": 130},
        "Facilities": ["Trade Market", "Refueling", "Repair Docks"],
        "Governance": "Corporate",
        "Tech Level": "High",
        "Security Level": "High",
        "Cultural Significance": "Moderate",
        "Trade Regulations": "Standard",
        "Access Restrictions": "None",
        "Research Opportunities": "Limited",
        "Strategic Importance": "Very High",
        "Health and Medical Facilities": "Advanced",
        "Entertainment and Leisure": ["Bars", "Restaurants", "Shopping Centers"],
        "Docking Capacity": "100 Ships",
        "Affiliation": "Neutral"
    },
    "Falcon_Military_Outpost": {
        "Name": "Falcon Military Outpost",
        "Type": "Military Outpost",
        "Size": "Medium",
        "Population": "Moderate",
        "Defense Capability": "High",
        "Economic Status": "Moderate",
        "Location": {"X": -320, "Y": 150, "Z": 75},
        "Facilities": ["Armory", "Barracks", "Tactical Command Center"],
        "Governance": "Military",
        "Tech Level": "Advanced",
        "Security Level": "Very High",
        "Cultural Significance": "Low",
        "Trade Regulations": "Strict",
        "Access Restrictions": "High",
        "Research Opportunities": "None",
        "Strategic Importance": "High",
        "Health and Medical Facilities": "Military Grade",
        "Entertainment and Leisure": ["Officer's Club"],
        "Docking Capacity": "50 Ships",
        "Affiliation": "Specific Faction"
    },
    "Zenith_Research_Facility": {
        "Name": "Zenith Research Facility",
        "Type": "Research Facility",
        "Size": "Small",
        "Population": "Low",
        "Defense Capability": "Light",
        "Economic Status": "Funded",
        "Location": {"X": 600, "Y": -100, "Z": 200},
        "Facilities": ["Laboratories", "Observatories", "Scholarly Archives"],
        "Governance": "Scientific Coalition",
        "Tech Level": "State-of-the-Art",
        "Security Level": "Moderate",
        "Cultural Significance": "High",
        "Trade Regulations": "Restricted",
        "Access Restrictions": "High",
        "Research Opportunities": "Extensive",
        "Strategic Importance": "Medium",
        "Health and Medical Facilities": "Specialized",
        "Entertainment and Leisure": ["Lecture Halls", "Galleries"],
        "Docking Capacity": "20 Ships",
        "Affiliation": "Academic"
    },
    "Orion_Refueling_Depot": {
        "Name": "Orion Refueling Depot",
        "Type": "Refueling Station",
        "Size": "Medium",
        "Population": "Moderate",
        "Defense Capability": "Moderate",
        "Economic Status": "Stable",
        "Location": {"X": -150, "Y": 250, "Z": 50},
        "Facilities": ["Fuel Reserves", "Maintenance Bays", "Supply Stores"],
        "Governance": "Corporate",
        "Tech Level": "Medium",
        "Security Level": "High",
        "Cultural Significance": "Low",
        "Trade Regulations": "Moderate",
        "Access Restrictions": "None",
        "Research Opportunities": "None",
        "Strategic Importance": "High",
        "Health and Medical Facilities": "Basic",
        "Entertainment and Leisure": ["Diners", "Recreation Rooms"],
        "Docking Capacity": "70 Ships",
        "Affiliation": "Neutral"
    }
}

